image: Visual Studio 2017

version: {branch}

clone_depth: 1

platform:
  - x64

artifacts:
  - path: build\win-unpacked
    name: painel-web-2.0.0-x64-win
    type: zip

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn run build

test: off

deploy:
  release: "{version}"
  description: "Painel Web {version}"
  provider: GitHub
  auth_token:
    secure: jAoBlzSLWDwiDEs7yaPJHvPr3rzz1+lyZw5n4XQfdQayg3qbWWGq+44+zOLyodha
  artifact: "build\painel-web-{version}-x64-win.zip"
  on:
    appveyor_repo_tag: true
