image: Visual Studio 2017

platform:
  - x64

artifacts:
  - path: build\win-unpacked
    name: painel-web
    type: zip

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn run build

test: off

deploy:
  release: painel-web-2.0.0-BETA
  description: 'Painel Web 2.0 beta'
  provider: GitHub
  auth_token:
    secure: jAoBlzSLWDwiDEs7yaPJHvPr3rzz1+lyZw5n4XQfdQayg3qbWWGq+44+zOLyodha
  artifact: painel-web.zip
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
