image: Visual Studio 2017

platform:
  - x64

artifacts:
  - path: build\win-unpacked
    name: Painel Web
    type: zip

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn run build

test: off
